<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SEPARATION" Id="{742462ac-1e27-4045-b59f-5171acd4e492}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SEPARATION
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SEPARATION">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>