<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ERROR_CODE" Id="{582f2577-f0f5-466d-8f42-319308e7f4ba}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ERROR_CODE
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ERROR_CODE">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>