<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MOTORS" Id="{16a50c5a-79ce-4927-aa8a-38fc0bc20c74}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MOTORS
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Axis_MAIN(sName:='MAIN');
Axis_SUPPLY(sNAme:='supply');
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>